services:
  rag-app:
    build: .
    container_name: rag-ecommerce
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./scripts:/app/scripts
    env_file:
      - .env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true